// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhjC2X0oXieOSPnEAVJ1RTSYVy4ajfH64',
    appId: '1:29246826903:web:79c32b83a7849426b23cd2',
    messagingSenderId: '29246826903',
    projectId: 'timetable-generation-app-57970',
    authDomain: 'timetable-generation-app-57970.firebaseapp.com',
    storageBucket: 'timetable-generation-app-57970.appspot.com',
    measurementId: 'G-X5NWR1ZFLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL5t1YqEZi3D-4swqmLM9P2RPhEDV64VM',
    appId: '1:29246826903:android:8b99130d4cada739b23cd2',
    messagingSenderId: '29246826903',
    projectId: 'timetable-generation-app-57970',
    storageBucket: 'timetable-generation-app-57970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJLVv0jsIhv3QmkE3rHywC8Begn9_6lwU',
    appId: '1:29246826903:ios:671bf447578181f4b23cd2',
    messagingSenderId: '29246826903',
    projectId: 'timetable-generation-app-57970',
    storageBucket: 'timetable-generation-app-57970.appspot.com',
    iosBundleId: 'com.example.timetableGenerationApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJLVv0jsIhv3QmkE3rHywC8Begn9_6lwU',
    appId: '1:29246826903:ios:671bf447578181f4b23cd2',
    messagingSenderId: '29246826903',
    projectId: 'timetable-generation-app-57970',
    storageBucket: 'timetable-generation-app-57970.appspot.com',
    iosBundleId: 'com.example.timetableGenerationApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhjC2X0oXieOSPnEAVJ1RTSYVy4ajfH64',
    appId: '1:29246826903:web:d753255f94db4ae0b23cd2',
    messagingSenderId: '29246826903',
    projectId: 'timetable-generation-app-57970',
    authDomain: 'timetable-generation-app-57970.firebaseapp.com',
    storageBucket: 'timetable-generation-app-57970.appspot.com',
    measurementId: 'G-PHW7E9LB8C',
  );
}
